language: java

jdk:
  - oraclejdk8

services:
  - redis-server

cache:
  directories:
    - $HOME/.m2
    - $HOME/.embedmongo

sudo: false

install: true

script: "mvn clean dependency:list test -Dsort"
